name: Build/release

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+.[0-9]+'


jobs:
  build-publish:
    runs-on: ubuntu-latest

    environment:
      name: PyPI
      url: https://pypi.org/project/django-odoo-orm/

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7
      - name: Build project
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry build
          poetry publish -u __token__ -p "$PYPI_TOKEN"
